# syntax=docker/dockerfile:1

FROM python:3.9-alpine

WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

EXPOSE 8000

ENTRYPOINT uvicorn llm.main:app --host 0.0.0.0 --port 8000 --reload

#CMD ["uvicorn", "main:app", "--reload"]